### ISSUE TITLE
Obsidian File Sync

### ISSUE THREAD

**Issue by sriza** [OnlyEver/onlyever_obsidian_sync#3]
**Tasks**

- [x] update file in obsidian
- [x] syncNote data api
- [x] verify API key
